language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t jayeshkhazari/docker-react -f Dockerfile.dev .

script:
  - docker run jayeshkhazari/docker-react npm run test -- --coverage
