sudo: required
services: 
  - docker

before_install:
  - docker build -t JayeshKHazari/docker-react -f Dockerfile.dev .

scripts:
  - docker run JayeshKHazari/docker-react npm run test -- --coverage
